name: Build and Test Nodejs

on:
  push:
    branches: main

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Set up Nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env: 
          CI: true

      - name: Upload build output
        uses: actions/upload-artifact@v4.6.2
        with:
          name: build-output
          path: dist/
          if-no-files-found: ignore

      - name: Check path in runner
        run: | 
          ls -al ~
          ls -al ~/.npm
          ls -al /

      - name: Check machine info
        run: |
          echo "Machine: $(uname -a)"
          echo "Home dir: $HOME"
          echo "Current dir: $(pwd)"
          echo "All files:"
          ls -la

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Download build output
        uses: actions/download-artifact@v4.2.1
        with:
          name: build-output
          path: ./dist

      - run: echo "Deploying..."
      