name: Example CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{matrix.os}}-node-${{matrix.node-version}}

      - name: Set up NodeJs ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with: 
          node-version: ${{matrix.node-version}}

      - name: Install dependencies and test
        run: |
          npm ci
          npm test

      - name: Build Docker Image
        run: |
          docker build -t quangdung2110/my-nodeapp .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Registry
        run: |
          docker push quangdung2110/my-nodeapp

      - name: Check structure of runner
        run: |
          ls -al /
          ls -al ~
          pwd
          whoami
          ls -al ~/.npm
          ls -al ~/.npm/_cacache
          ls -al ~/.npm/_logs
      
