name: Example CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu:latest

    strategy:
      matrix:
        - version: [22.x]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3

      - name: Set up NodeJs ${{matrix.version}}
        uses: actions/setup-node@v4

      - name: Install dependencies and test
        run: |
          npm ci
          npm test

      - name: Build Docker Image
        run: |
          docker build -t quangdung2110/my-nodeapp ./Dockerfile
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Registry
        run: |
          docker push quangdung2110/my-nodeapp
      
      - name: Deploy 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull quangdung2110/my-nodeapp
            docker stop app || true && docker rm app || true
            docker run -d --name app -p 3000:3000 quangdung2110/my-nodeapp
